/**
 * Created by wenboliu on 05/09/2024.
 */

public inherited sharing class Constant {
    public static final String BITLY_API_ENDPOINT_NAME= 'BITLY_API_ENDPOINT_NAME';
    public static final String BITLY_API_CLIENT_ID_SETTING_NAME = 'BITLY_API_CLIENT_ID_SETTING_NAME';
    public static final String BITLY_API_CLIENT_SECRET_SETTING_NAME = 'BITLY_API_CLIENT_SECRET_SETTING_NAME';
    public static final String BITLY_API_USER_NAME_NAME= 'BITLY_API_USER_NAME_NAME';
    public static final String BITLY_API_PASSWORD_NAME= 'BITLY_API_PASSWORD_NAME';
    public static final String GOOGLE_CONFIG_NAME = 'GoogleConfig';

}